### ISSUE TITLE
Huge bundle size

### ISSUE THREAD

**Issue by Gerald12344** [konradkalemba/tabler-icons-react#10]
![image](https://user-images.githubusercontent.com/29782882/170994682-157bb0ce-008b-4583-b0c5-16ee725e6c61.png)
I import it using code like 
```ts
import { Archive, ShoppingCartDiscount, Trash } from 'tabler-icons-react';
```
but somehow the whole library is added to the bundle what am I doing wrong?

**Comment by konradkalemba** [comment]
@Gerald12344 Thank you for the report. It seems that "tree-shakeability" wasn't properly implemented and the bundler in your project couldn't exclude not used icons.

Could you try installing newest version and check if it works properly now? 
```bash
npm i tabler-icons-react@1.48.1
```

**Comment by feledori** [comment]
@konradkalemba I just tested the new version and it fixed the issue. At least on my project. Thanks!

**Comment by Gerald12344** [comment]
> Could you try installing newest version and check if it works properly now?

 Will do tonight thanks
