### ISSUE TITLE
Rename or prepend the names of the icon components. 

### ISSUE THREAD

**Issue by Vizorous** [konradkalemba/tabler-icons-react#11]
As it stands, this library contains icons with the exact names used by many popular component libraries.
e.g. :- Container, Menu, Table, Tag, Space, Stack, Album, Align, Box.

It's suffice to say that it is quite annoying to develop when you're accidently importing the wrong component every time you auto import a heavily used component like Container from basically any UI library and you get an icon as the import rather than the actual component. 
 
I would like to suggest to prepend the names of the icon components with a word like "Tabler" so it would say "TablerContainer" instead of Container. This will eliminate the issues with imports.

**Comment by konradkalemba** [comment]
I understand your issue, however as of today I don't plan to change the naming of the icons because it would result in a breaking change.
