### ISSUE TITLE
Forward Ref Error because of Link component

### ISSUE THREAD

**Issue by blyxyas** [konradkalemba/tabler-icons-react#12]
(Using Next.js)

In the client console it warns the following:

Warning: Function components cannot be given refs. Attemps to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ForwardRef`.

After some troubleshooting I've came to the conclusion that the `Link` from `next/link` is the cause of this error, is there a solution?

**Comment by konradkalemba** [comment]
I believe you have to wrap icon component with React.forwardRef function like presented in [Next.js documentation](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-functional-component). I'm currently away from computer, so unfortunately I can't help you more here.
