### ISSUE TITLE
Provide a way to set a default color for all icons

### ISSUE THREAD

**Issue by mcmxcdev** [konradkalemba/tabler-icons-react#13]
We have business requirements that all icons should use some kind of purple color and you can imagine how tedious this gets when you need to specify it on each icon individually.

Is there a way to set a default color that all icons inherit? Ideally, it should still be overwritable.

**Comment by konradkalemba** [comment]
This is currently not supported, however all icons have `currentColor` set as their stroke color by default, so I believe a workaround could be setting a global css rule like so:
```css
svg.icon-tabler {
    color: purple;
}
```

**Comment by mcmxcdev** [comment]
Thanks Konrad, I will try that out!
