### ISSUE TITLE
Get icon by string

### ISSUE THREAD

**Issue by pascal-adk** [konradkalemba/tabler-icons-react#14]
Hello,
In my database, I need to store the icons as a string like "shoe" or "x".
But if I want them in my DOM, I need to build something like this:
```js
import { Shoe, X } from "tabler-icons-react";
const data = {
    shoe: Shoe,
    x: X,
}

const selectedIcon = data["shoe"];
```

Is there an easier way? 
Greetings, PixelPage

**Comment by m-bp** [comment]
This is what you want:

```jsx
import * as data from "tabler-icons-react";

const SelectedIcon = data["Shoe"]; // Keep in mind the name is the same as the element, caps included

<SelectedIcon />
```

But it will load the entire library into your bundle so it's not ideal.

If you want to avoid that you could probably use the .svg files directly from the `tabler-icons` library and use them like so:

```jsx
const icon = "shoe"
<img src={`/icons/${icon}.svg`} />
```
To avoid putting the entire .svg library in my repo I use webpack's copy plugin to copy the .svg folder directly from my `/node_modules` and into my public folder when building the app. Depending on your setup you might do something else. Hell, you could use a bash script. 

This is how I copy Material UI's icons in my NextJS config:

```js
{
  // ...
  webpack: config => {
    config.plugins.push(
      new CopyPlugin({
        patterns: [
          {
            from: path.join(
              __dirname,
              "node_modules/@material-design-icons/svg/filled"
            ),
            to: path.join(__dirname, "public/icons"),
          },
        ],
      })
    )

    return config
  },
  // ...
}
```

And ofc make sure to put the folder in your `.gitignore`

**Comment by konradkalemba** [comment]
Closing as this package is no longer maintained as there is now an official package. Please see https://tabler.io/docs/icons/react
