### ISSUE TITLE
Failed resolve 

### ISSUE THREAD

**Issue by Youssef535** [konradkalemba/tabler-icons-react#17]
**Hello** I work on a project with mantine and React tsx  and when i import the icon i receive and error 
` Failed to resolve import "@tabler/icons-react" from "src\components\Recover.tsx". Does the file exist?` 

How can i solve this problem?

**Problem solved I was not using the lastest version of tabler.**

**Comment by konradkalemba** [comment]
Hey @Youssef535,

I'm glad your issue is solved now. Just a little heads up – this is a repository for package named `tabler-icons-react`, while your issue seems to be with `@tabler/icons-react`. For future issues please see its repository https://github.com/tabler/tabler-icons
